name: Main

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, cargo-nextest
          profile: minimal
          override: true

      # selecting a toolchain should happen before the plugin, as the cache uses the current rustc version as its cache key
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: just lint

      - name: Test
        run: just test-all

      - name: Audit dependencies
        run: |
          cargo install --locked cargo-audit
          cargo audit
